.TH pmac 8 "3 March 2012"
.SH NAME
pmac \- proper MAC address generator and changer
.SH SYNOPSIS
.B pmac
[ { \-h | \-\-help } ]
[ { \-l | \-\-list } ]
[ { \-i | \-\-interface } int ]
[ { \-v | \-\-vendor } name ]
[ { \-m | \-\-manually } address ]
[ { \-f | \-\-force } ]
[ { \-p | \-\-print } ]
.SH DESCRIPTION
